# Monitor
monitor = ,1920x1080@60,auto,1

# Applications
$terminal = kitty

# Startup
exec-once = $terminal

# Keybindings
bind = SUPER, Q, exec, $terminal
bind = SUPER, C, killactive
bind = SUPER, M, exit
