wallpaper {
    monitor =

    # ── Selecciona un wallpaper ──
    # path = ~/.config/hypr/wallpapers/wallhaven-42erkg_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-49q83x_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-7pkp3o_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-mpllq9_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-pogjve_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-qzpdz7_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-w5o7r6_1920x1080.png
    # path = ~/.config/hypr/wallpapers/wallhaven-xe9jdo_1920x1080.png
      path = ~/.config/hypr/wallpapers/wallhaven-yq872g_1920x1080.png

    fit_mode = cover
}

splash = false
