# Fuente
font_family      ZedMono Nerd Font Mono
bold_font        auto
italic_font      auto
font_size        14.0
modify_font      cell_height 110%

# Ventana
window_padding_width 12 16
hide_window_decorations yes
background_opacity 0.90
background_blur 32
dynamic_background_opacity yes
confirm_os_window_close 0

# Cursor
cursor_shape beam
cursor_beam_thickness 2.0
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
cursor_trail 3
cursor_trail_decay 0.1 0.4

# Barra de pestañas
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     round
tab_bar_min_tabs        2
active_tab_font_style   bold
tab_title_template      " {index}: {title[:20]} "

# Bordes de splits
window_border_width     1pt
inactive_text_alpha     0.75

# Campana
enable_audio_bell no
visual_bell_duration 0.0

# Varios
scrollback_lines 10000
url_style curly
copy_on_select clipboard
disable_ligatures never

# Colores de respaldo (el tema los sobrescribe si los define)
active_tab_foreground   #120D1A
active_tab_background   #B983FF
inactive_tab_foreground #DDD1EA
inactive_tab_background #21152E
tab_bar_background      #120D1A
active_border_color     #B983FF
inactive_border_color   #60456F
mark1_foreground        #120D1A
mark1_background        #FF668C
url_color               #B983FF

# Tema activo (deja solo uno)
# include purple-night.conf
 include purple-violet.conf
# include purple-lavender.conf
# include catppuccin-mocha.conf
# include dracula.conf
# include rose-pine.conf
# include tokyo-night.conf
