# Purple Night

foreground              #E9E1F5
background              #17131F

cursor                  #C4A7FF
cursor_text_color       #17131F

selection_foreground    #17131F
selection_background    #C4A7FF

# Normal colors
color0                  #211B2B
color1                  #E06C75
color2                  #98C379
color3                  #E5C07B
color4                  #61AFEF
color5                  #A879E6
color6                  #56B6C2
color7                  #D8D0E3

# Bright colors
color8                  #5C526A
color9                  #FF7B86
color10                 #B5E28C
color11                 #F5D98B
color12                 #7CBFFF
color13                 #C69AFF
color14                 #70D9E5
color15                 #F5EFFB
