# Plum & Lavender

foreground              #F3EAF7
background              #1A111C

cursor                  #D0A6FF
cursor_text_color       #1A111C

selection_foreground    #1A111C
selection_background    #D0A6FF

# Normal colors
color0                  #271A29
color1                  #E87991
color2                  #9BCB9B
color3                  #E6C98F
color4                  #8DA4D9
color5                  #C084FC
color6                  #8CC9C9
color7                  #DED2E0

# Bright colors
color8                  #69536B
color9                  #F59AAF
color10                 #B5E2B5
color11                 #F4DCA8
color12                 #AFC3F5
color13                 #D6A5FF
color14                 #A9E5E5
color15                 #FFF7FF

