# Neon Violet

foreground              #F2EAFE
background              #120D1A

cursor                  #B983FF
cursor_text_color       #120D1A

selection_foreground    #120D1A
selection_background    #B983FF

# Normal colors
color0                  #21152E
color1                  #FF668C
color2                  #72E0A0
color3                  #F3C969
color4                  #7AA2F7
color5                  #B56CFF
color6                  #5ED7E8
color7                  #DDD1EA

# Bright colors
color8                  #60456F
color9                  #FF8EAA
color10                 #91F2B7
color11                 #FFE28C
color12                 #9DBBFF
color13                 #D08FFF
color14                 #83EAF5
color15                 #FFFFFF
